name: Deploy to Servers

on:
  push:
    branches:
      - projectA
      - projectB
      - projectC

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Checkout main branch for server list
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch

      - name: Set up SSH key for infadata user
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.INFADATA_SSH_PRIVATE_KEY }}

      - name: Determine environment and server list
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          ENVIRONMENT=$(echo $BRANCH_NAME | sed 's/project[A-C]//')
          SERVER_LIST_FILE="${ENVIRONMENT}_servers_list.txt"
          SERVERS=$(cat main-branch/$SERVER_LIST_FILE)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "SERVERS=$SERVERS" >> $GITHUB_ENV

      - name: Sync scripts
        run: |
          if [[ -n $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep "scripts/") ]]; then
            for SERVER in $SERVERS; do
              rsync -avz --update $BRANCH_NAME/$BRANCH_NAME/$ENVIRONMENT/scripts/ infadata@$SERVER:/var/data/infadata/shell/
            done
          else
            echo "Scripts folder not modified. Skipping sync."
          fi

      - name: Sync config
        run: |
          if [[ -n $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep "config/") ]]; then
            for SERVER in $SERVERS; do
              rsync -avz --update $BRANCH_NAME/$BRANCH_NAME/$ENVIRONMENT/config/ infadata@$SERVER:/var/data/infadata/config/
            done
          else
            echo "Config folder not modified. Skipping sync."
          fi
